name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential meson ninja-build

    - name: Configure Meson
      run: meson setup build

    - name: Build project
      run: meson compile -C build

    - name: Run app
      run: |
        ./build/app/crc32-app README.md
